select DATEDIFF(MONTH, START_DATE, FINISH_DATE) * sum(WORKER.SALARY) as PRICE, PW.PROJECT_ID
from WORKER
         JOIN PUBLIC.PROJECT_WORKER PW
              on WORKER.ID = PW.WORKER_ID
         JOIN PROJECT
on PW.PROJECT_ID = PROJECT.ID
     group by PW.PROJECT_ID;
